//0 - nutrition, 1 - beauty, 2 - lifestyle

export const channelMapping = [
  { channelName: 'exant', brandName: 'Exante', div: 0, total: 0 },
  { channelName: 'massint', brandName: 'Mass', div: 0, total: 0 },
  { channelName: 'myprotein', brandName: 'My Protein', div: 0, total: 0 },
  { channelName: 'myvegan', brandName: 'My Vegan', div: 0, total: 0 },
  { channelName: 'myvitamins', brandName: 'My Vitamins', div: 0, total: 0 },
  // { channelName: 'idealfit', brandName: 'IdealFit', div: 0, total: 0 },
  // { channelName: 'idealshape', brandName: 'IdealShape', div: 0, total: 0 },
  // { channelName: 'idealraw', brandName: 'IdealRaw', div: 0, total: 0 },
  // { channelName: 'optifast', brandName: 'Optiast', div: 0, total: 0 },
  // { channelName: 'comvita', brandName: 'Comvita', div: 0, total: 0 },
  // { channelName: 'mypronutri', brandName: 'Mypronutri', div: 0, total: 0 },
  // {
  //   channelName: 'trrnutrition',
  //   brandName: 'TRR Nutrition',
  //   div: 0,
  //   total: 0,
  // },
  // { channelName: 'lqcollagen', brandName: '', div: 0, total: 0 },
  // { channelName: 'bonrawfoods', brandName: '', div: 0, total: 0 },
  // { channelName: 'precbiotics', brandName: '', div: 0, total: 0 },
  // { channelName: 'vitalpro', brandName: '', div: 0, total: 0 },
  // { channelName: 'mightypea', brandName: '', div: 0, total: 0 },
  // { channelName: 'puritans', brandName: '', div: 0, total: 0 },
  // { channelName: 'boostball', brandName: '', div: 0, total: 0 },
  // { channelName: 'bimuno', brandName: '', div: 0, total: 0 },
  // { channelName: 'nutrimuscle', brandName: '', div: 0, total: 0 },
  // { channelName: 'advancednutr', brandName: '', div: 0, total: 0 },
  // { channelName: 'myrkl', brandName: '', div: 0, total: 0 },
  // { channelName: 'myomega', brandName: '', div: 0, total: 0 },
  // { channelName: 'sfihealth', brandName: '', div: 0, total: 0 },
  // { channelName: 'eontea', brandName: '', div: 0, total: 0 },
  // { channelName: 'benu', brandName: '', div: 0, total: 0 },
  // { channelName: 'celebslim', brandName: '', div: 0, total: 0 },
  // { channelName: 'fibreone', brandName: '', div: 0, total: 0 },
  // { channelName: 'tinglyteds', brandName: '', div: 0, total: 0 },
  // { channelName: 'blackmores', brandName: '', div: 0, total: 0 },
  // { channelName: 'skinnybrands', brandName: '', div: 0, total: 0 },
  // { channelName: 'nzmuscle', brandName: '', div: 0, total: 0 },
  // { channelName: 'abouttime', brandName: '', div: 0, total: 0 },
  // { channelName: 'haircarebear', brandName: '', div: 0, total: 0 },
  // { channelName: 'plasmon', brandName: '', div: 0, total: 0 },
  // { channelName: 'gol', brandName: '', div: 0, total: 0 },
  // { channelName: 'maint', brandName: '', div: 0, total: 0 },
  // { channelName: 'ccdirect', brandName: '', div: 0, total: 0 },
  // { channelName: 'heinz', brandName: '', div: 0, total: 0 },
  // { channelName: 'everyhealth', brandName: '', div: 0, total: 0 },
  { channelName: 'ryint', brandName: 'Recreate Yourself', div: 1, total: 0 },
  // { channelName: 'beautysleuth', brandName: '', div: 1, total: 0 },
  // { channelName: 'elemis', brandName: 'Elemis', div: 1, total: 0 },
  {
    channelName: 'christopherobin',
    brandName: 'Christophe Robin',
    div: 1,
    total: 0,
  },
  { channelName: 'ameliorate', brandName: 'Ameliorate', div: 1, total: 0 },
  { channelName: 'glossybox', brandName: 'GlossyBox', div: 1, total: 0 },
  { channelName: 'lfint', brandName: 'LookFantastic', div: 1, total: 0 },
  { channelName: 'perriconemd', brandName: 'Perricone MD', div: 1, total: 0 },
  // { channelName: 'andalounatur', brandName: '', div: 1, total: 0 },
  // { channelName: 'percentpure', brandName: '', div: 1, total: 0 },
  { channelName: 'mamamio', brandName: 'Mama Mio', div: 1, total: 0 },
  {
    channelName: 'growgorgeous',
    brandName: 'Grow Gorgeous',
    div: 1,
    total: 0,
  },
  // { channelName: 'washbag', brandName: 'Washbag', div: 1, total: 0 },
  {
    channelName: 'beautyexpert',
    brandName: 'Beauty Expert',
    div: 1,
    total: 0,
  },
  { channelName: 'mankind', brandName: 'Mankind', div: 1, total: 0 },
  { channelName: 'hqhair', brandName: 'HQHair', div: 1, total: 0 },
  { channelName: 'mio', brandName: 'Mio Skincare', div: 1, total: 0 },
  // { channelName: 'shuuemura', brandName: 'Shu Uemura', div: 1, total: 0 },
  { channelName: 'mious', brandName: 'Mio Skincare', div: 1, total: 0 },
  // { channelName: 'lancer', brandName: 'Lancer Skincare', div: 1, total: 0 },
  // {
  //   channelName: 'lancerskin',
  //   brandName: 'Lancer Skincare',
  //   div: 1,
  //   total: 0,
  // },
  // { channelName: 'opi', brandName: 'OPI', div: 1, total: 0 },
  // { channelName: 'erborian', brandName: 'Erborian', div: 1, total: 0 },
  // { channelName: 'koparibeauty', brandName: '', div: 1, total: 0 },
  // { channelName: 'babor', brandName: 'Babor', div: 1, total: 0 },
  // { channelName: 'watermans', brandName: 'Watermans Hair', div: 1, total: 0 },
  // { channelName: 'wella', brandName: 'Wella', div: 1, total: 0 },
  { channelName: 'cbeauty', brandName: 'Cult Beauty', div: 1, total: 0 },
  // {
  //   channelName: 'revbeauty',
  //   brandName: 'Revolution Beauty',
  //   div: 1,
  //   total: 0,
  // },
  // {
  //   channelName: 'barberbarber',
  //   brandName: 'Daimon Barber',
  //   div: 1,
  //   total: 0,
  // },
  // { channelName: 'revlon', brandName: 'Revlon', div: 1, total: 0 },
  // { channelName: 'smartgirls', brandName: '', div: 1, total: 0 },
  // { channelName: 'frankbody', brandName: 'Frank Body', div: 1, total: 0 },
  // { channelName: 'byterry', brandName: 'By Terry', div: 1, total: 0 },
  // { channelName: 'oraskincare', brandName: 'ORA Skincare', div: 1, total: 0 },
  // { channelName: 'pnselfcare', brandName: 'PN Selfcare', div: 1, total: 0 },
  // { channelName: 'naturabisse', brandName: 'Natura Bisse', div: 1, total: 0 },
  // {
  //   channelName: 'crystalclear',
  //   brandName: 'Crystal Clear',
  //   div: 1,
  //   total: 0,
  // },
  // {
  //   channelName: 'artdeco',
  //   brandName: 'Artdeco Cosmetics',
  //   div: 1,
  //   total: 0,
  // },
  // { channelName: 'plenaire', brandName: 'Plenaire', div: 1, total: 0 },
  // { channelName: 'haoma', brandName: 'Haoma', div: 1, total: 0 },
  // { channelName: 'acoskincare', brandName: 'ACO Skincare', div: 1, total: 0 },
  // { channelName: 'moltonbrown', brandName: 'Molton Brown', div: 1, total: 0 },
  // { channelName: 'shiro', brandName: 'Shiro', div: 1, total: 0 },
  // { channelName: 'indielee', brandName: 'Indie Lee', div: 1, total: 0 },
  // { channelName: 'spectriskin', brandName: 'SpectriSKIN', div: 1, total: 0 },
  // { channelName: 'freezeframe', brandName: 'Freeze Frame', div: 1, total: 0 },
  // { channelName: 'biokult', brandName: 'Bio-Kult', div: 1, total: 0 },
  // { channelName: 'ultabeauty', brandName: 'UltaBeauty', div: 1, total: 0 },
  // { channelName: 'eyeko', brandName: 'Eyeko', div: 1, total: 0 },
  // {
  //   channelName: 'unexpekted',
  //   brandName: 'The Unexpekted',
  //   div: 1,
  //   total: 0,
  // },
  // { channelName: 'amika', brandName: 'Amika', div: 1, total: 0 },
  // { channelName: 'drbrandt', brandName: 'DrBrant', div: 1, total: 0 },
  // { channelName: 'inika', brandName: 'Inika', div: 1, total: 0 },
  // { channelName: 'drybar', brandName: 'Drybar', div: 1, total: 0 },
  // { channelName: 'bhcosmetics', brandName: 'BH Cosmetics', div: 1, total: 0 },
  // { channelName: 'bellewave', brandName: 'Bellewave', div: 1, total: 0 },
  // {
  //   channelName: 'anastasiabh',
  //   brandName: 'Anastasia Beverly Hills',
  //   div: 1,
  //   total: 0,
  // },
  // {
  //   channelName: 'athletiabeau',
  //   brandName: 'Athletia Beauty',
  //   div: 1,
  //   total: 0,
  // },
  // { channelName: 'filorga', brandName: 'Filorga', div: 1, total: 0 },
  // { channelName: 'korres', brandName: 'Korres', div: 1, total: 0 },
  // { channelName: 'sknhead', brandName: 'Sknhead', div: 1, total: 0 },
  // { channelName: 'lfusa', brandName: 'LookFantastic', div: 1, total: 0 },
  // { channelName: 'coverfx', brandName: 'CoverFX', div: 1, total: 0 },
  // {
  //   channelName: 'lihtorganics',
  //   brandName: 'Liht Organics',
  //   div: 1,
  //   total: 0,
  // },
  { channelName: 'skinstore', brandName: 'SkinStore', div: 1, total: 0 },
  // {
  //   channelName: 'secretos',
  //   brandName: 'Secretos del Agua',
  //   div: 1,
  //   total: 0,
  // },
  // { channelName: 'kayobody', brandName: 'Kayo Bodycare', div: 1, total: 0 },
  // { channelName: 'skinvirtue', brandName: 'Skin Virtue', div: 1, total: 0 },
  // {
  //   channelName: 'whoiselijah',
  //   brandName: 'Who Is Elijah',
  //   div: 1,
  //   total: 0,
  // },
  // { channelName: 'symbiome', brandName: 'Symbiome', div: 1, total: 0 },
  // {
  //   channelName: 'fragrancedir',
  //   brandName: 'Fragrance Direct',
  //   div: 1,
  //   total: 0,
  // },
  // { channelName: 'allbeauty', brandName: 'AllBeauty', div: 1, total: 0 },
  {
    channelName: 'lfcn',
    brandName: 'LookFantastic',
    div: 1,
    total: 0,
  },
  // { channelName: 'pceuro', brandName: 'Paulas Choice', div: 1, total: 0 },
  // { channelName: 'rabot', brandName: '', div: 1, total: 0 },
  // { channelName: 'yol', brandName: 'Yardley of London', div: 1, total: 0 },
  // { channelName: 'oralb', brandName: 'Oral B', div: 1, total: 0 },
  { channelName: 'illamasqua', brandName: 'Illamasqua', div: 1, total: 0 },
  // { channelName: 'noseven', brandName: 'No7', div: 1, total: 0 },
  // { channelName: 'neutral', brandName: 'Neutral', div: 1, total: 0 },
  // { channelName: 'snowberry', brandName: 'Snowberry', div: 1, total: 0 },
  // { channelName: 'eaint', brandName: 'Elizabeth Arden', div: 1, total: 0 },
  { channelName: 'espa', brandName: 'Espa', div: 1, total: 0 },
  // { channelName: 'braun', brandName: 'Braun', div: 1, total: 0 },
  // { channelName: 'gillette', brandName: 'Gillette', div: 1, total: 0 },
  { channelName: 'dermstore', brandName: 'Dermstore', div: 1, total: 0 },
  // { channelName: 'nuxe', brandName: 'Nuxe', div: 1, total: 0 },
  // { channelName: 'zyn', brandName: 'Zyn', div: 2, total: 0 },
  // { channelName: 'homebase', brandName: 'Homebase', div: 2, total: 0 },
  { channelName: 'hut', brandName: 'The Hut', div: 2, total: 0 },
  // { channelName: 'vimto', brandName: 'Vimto', div: 2, total: 0 },
  // { channelName: 'toblerone', brandName: 'Toblerone', div: 2, total: 0 },
  // { channelName: 'croquonslavi', brandName: '', div: 2, total: 0 },
  // { channelName: 'speedo', brandName: '', div: 2, total: 0 },
  // { channelName: 'zenrc', brandName: '', div: 2, total: 0 },
  // { channelName: 'bathstoreuat', brandName: '', div: 2, total: 0 },
  // { channelName: 'rednoseday', brandName: '', div: 2, total: 0 },
  // { channelName: 'berghaus', brandName: '', div: 2, total: 0 },
  // { channelName: 'lyleandscott', brandName: '', div: 2, total: 0 },
  // { channelName: 'clogauoutlet', brandName: '', div: 2, total: 0 },
  // { channelName: 'purinabeta', brandName: '', div: 2, total: 0 },
  // { channelName: 'kickers', brandName: '', div: 2, total: 0 },
  // { channelName: 'thgtraining', brandName: '', div: 2, total: 0 },
  // { channelName: 'handmadesoap', brandName: '', div: 2, total: 0 },
  // { channelName: 'gracecole', brandName: '', div: 2, total: 0 },
  // { channelName: 'ellesse', brandName: '', div: 2, total: 0 },
  // { channelName: 'elevendegree', brandName: '', div: 2, total: 0 },
  // { channelName: 'naturestruth', brandName: '', div: 2, total: 0 },
  // { channelName: 'fetwentyone', brandName: '', div: 2, total: 0 },
  // { channelName: 'canterbury', brandName: '', div: 2, total: 0 },
  // { channelName: 'pureiscbd', brandName: '', div: 2, total: 0 },
  // { channelName: 'unishop', brandName: '', div: 2, total: 0 },
  // { channelName: 'rubyanddaisy', brandName: '', div: 2, total: 0 },
  // { channelName: 'endurasport', brandName: '', div: 2, total: 0 },
  // { channelName: 'jonrichard', brandName: '', div: 2, total: 0 },
  // { channelName: 'mitre', brandName: '', div: 2, total: 0 },
  // { channelName: 'hpeactive', brandName: '', div: 2, total: 0 },
  // { channelName: 'esprit', brandName: 'Esprit', div: 2, total: 0 },
  // { channelName: 'otocbd', brandName: '', div: 2, total: 0 },
  // { channelName: 'dgwellwear', brandName: '', div: 2, total: 0 },
  // { channelName: 'lesgirlslesb', brandName: '', div: 2, total: 0 },
  // { channelName: 'cargods', brandName: '', div: 2, total: 0 },
  // { channelName: 'deliverance', brandName: '', div: 2, total: 0 },
  // { channelName: 'ecomodern', brandName: '', div: 2, total: 0 },
  // { channelName: 'babyandme', brandName: '', div: 2, total: 0 },
  // { channelName: 'nobull', brandName: '', div: 2, total: 0 },
  // { channelName: 'adameve', brandName: '', div: 2, total: 0 },
  // { channelName: 'gearbox', brandName: '', div: 2, total: 0 },
  // { channelName: 'jerseyhemp', brandName: '', div: 2, total: 0 },
  // { channelName: 'rockandroll', brandName: '', div: 2, total: 0 },
  // { channelName: 'sandbox', brandName: '', div: 2, total: 0 },
  // { channelName: 'spectrumc', brandName: '', div: 2, total: 0 },
  // { channelName: 'beggxco', brandName: '', div: 2, total: 0 },
  // { channelName: 'millican', brandName: '', div: 2, total: 0 },
  // { channelName: 'prolong', brandName: '', div: 2, total: 0 },
  // { channelName: 'julesleblanc', brandName: '', div: 2, total: 0 },
  // { channelName: 'oneskee', brandName: '', div: 2, total: 0 },
  // { channelName: 'bornprim', brandName: '', div: 2, total: 0 },
  // { channelName: 'quicksci', brandName: '', div: 2, total: 0 },
  // { channelName: 'darceyscan', brandName: '', div: 2, total: 0 },
  // { channelName: 'matalan', brandName: 'Matalan', div: 2, total: 0 },
  // { channelName: 'movementum', brandName: '', div: 2, total: 0 },
  { channelName: 'coggles', brandName: 'Coggles', div: 2, total: 0 },
  // { channelName: 'snow', brandName: '', div: 2, total: 0 },
  // { channelName: 'celio', brandName: '', div: 2, total: 0 },
  // { channelName: 'fsbrand', brandName: '', div: 2, total: 0 },
  // { channelName: 'kersaintcobb', brandName: '', div: 2, total: 0 },
  // { channelName: 'equinepre', brandName: '', div: 2, total: 0 },
  // { channelName: 'whitestuff', brandName: 'White Stuff', div: 2, total: 0 },
  // { channelName: 'venus', brandName: 'Gillette Venus', div: 2, total: 0 },
  // { channelName: 'honda', brandName: 'Honda', div: 2, total: 0 },
  // {
  //   channelName: 'manutd',
  //   brandName: 'Manchester United Store',
  //   div: 2,
  //   total: 0,
  // },
  // { channelName: 'sportdiscount', brandName: '', div: 2, total: 0 },
  // { channelName: 'zavvi', brandName: 'Zavvi', div: 2, total: 0 },
  // { channelName: 'ninint', brandName: '', div: 2, total: 0 },
  // { channelName: 'hupping', brandName: '', div: 2, total: 0 },
  { channelName: 'pmint', brandName: 'LOAD TESTS', div: 2, total: 0 },
  // { channelName: 'gifted', brandName: '', div: 2, total: 0 },
  { channelName: 'popinabox', brandName: 'Pop In A Box', div: 2, total: 0 },
  { channelName: 'mygeekbox', brandName: 'My Geek Box', div: 2, total: 0 },
  // { channelName: 'urbrt', brandName: '', div: 2, total: 0 },
  // { channelName: 'insync', brandName: '', div: 2, total: 0 },
  // { channelName: 'copa90', brandName: '', div: 2, total: 0 },
  // { channelName: 'lftmall', brandName: '', div: 2, total: 0 },
  // { channelName: 'jigsaw', brandName: 'Jigsaw', div: 2, total: 0 },
  // { channelName: 'mrsbowtie', brandName: '', div: 2, total: 0 },
  // { channelName: 'jackwills', brandName: 'Jack Wills', div: 2, total: 0 },
  // { channelName: 'leverdirect', brandName: '', div: 2, total: 0 },
  // { channelName: 'purinabreeders', brandName: '', div: 2, total: 0 },
  // { channelName: 'purinaowners', brandName: '', div: 2, total: 0 },
  // { channelName: 'purinadirect', brandName: '', div: 2, total: 0 },
  // { channelName: 'purinashop', brandName: '', div: 2, total: 0 },
  // { channelName: 'purinavet', brandName: '', div: 2, total: 0 },
  // { channelName: 'purinaivc', brandName: '', div: 2, total: 0 },
  { channelName: 'allsole', brandName: 'Allsole', div: 2, total: 0 },
  // { channelName: 'zavviint', brandName: 'Zavvi', div: 2, total: 0 },
  // { channelName: 'xiwoot', brandName: 'IWOOT', div: 2, total: 0 },
  // { channelName: 'mylabel', brandName: '', div: 2, total: 0 },
  { channelName: 'mybag', brandName: 'MyBag', div: 2, total: 0 },
  // { channelName: 'veryneko', brandName: 'VeryNeko', div: 2, total: 0 },
  // { channelName: 'kellica', brandName: 'Kellica', div: 2, total: 0 },
  // { channelName: 'lavazza', brandName: 'Lavazza', div: 2, total: 0 },
  // { channelName: 'lorespresso', brandName: 'Lor Espresso', div: 2, total: 0 },
  { channelName: 'mypclothing', brandName: 'MP', div: 2, total: 0 },
  { channelName: 'hale', brandName: 'Hale', div: 2, total: 0 },
  { channelName: 'ingenuity', brandName: 'THG Ingenuity', div: 3, total: 0 },
];

export function getDivisionFromChannel(channel) {
  //if channel is in the list, get the division number
  const channelIndex = channelMapping.findIndex(
    channelObject => channelObject.channelName === channel,
  );
  if (channelIndex > -1) {
    return channelMapping[channelIndex].div;
  } else {
    return 2;
  }
}
